version: 2.1

parameters:
  run-foo:
    type: boolean
    default: false
  run-bar:
    type: boolean
    default: false
  run-baz:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.0

workflows:
  foo:
    when: << pipeline.parameters.run-foo >>
    jobs:
      - node/test:
          app-dir: packages/foo
  bar:
    when: << pipeline.parameters.run-bar >>
    jobs:
      - node/test:
          app-dir: packages/bar
  baz:
    when: << pipeline.parameters.run-baz >>
    jobs:
      - node/test:
          app-dir: packages/baz
