version: 2.1

parameters:
  run-foo:
    type: boolean
    default: false
  run-bar:
    type: boolean
    default: false
  run-baz:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.0

jobs:
  foo:
    steps:
      when: << pipeline.parameters.run-foo >>
      steps:
        run:
          command: npm ci && npm test
          working_directory: packages/foo
  bar:
    steps:
      when: << pipeline.parameters.run-bar >>
      steps:
        run:
          command: npm ci && npm test
          working_directory: packages/bar
  baz:
    steps:
      when: << pipeline.parameters.run-baz >>
      steps:
        run:
          command: npm ci && npm test
          working_directory: packages/baz

workflows:
  build-run:
    jobs:
      - foo
      - bar
      - baz
