version: 2.1

parameters:
  run-foo:
    type: boolean
    default: false
  run-bar:
    type: boolean
    default: false
  run-baz:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.0

workflows:
  build-run:
  jobs:
    - node/test:
        when: << pipeline.parameters.run-foo >>
    - node/test:
        when: << pipeline.parameters.run-bar >>
    - node/test:
        when: << pipeline.parameters.run-baz >>
