version: 2.1

parameters:
  run-foo:
    type: boolean
    default: false
  run-bar:
    type: boolean
    default: false
  run-baz:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.0

jobs:
  foo:
    executor: node/default
    steps:
      - when:
          condition: << pipeline.parameters.run-foo >>
          steps:
            - checkout
            - run:
                command: npm ci && npm test
                working_directory: packages/foo
  bar:
    executor: node/default
    steps:
      - when:
          condition: << pipeline.parameters.run-baz >>
          steps:
            - checkout
            - run:
                command: npm ci && npm test
                working_directory: packages/baz
  baz:
    executor: node/default
    steps:
      - when:
          condition: << pipeline.parameters.run-bar >>
          steps:
            - checkout
            - run:
                command: npm ci && npm test
                working_directory: packages/bar

workflows:
  build-run:
    jobs:
      - foo
      - bar
      - baz
