version: 2.1

orbs:
  composer: stockfiller/composer@1.0.0

parameters:
  php-modified:
    type: boolean
    default: false
  js-modified:
    type: boolean
    default: false
  e2e-modified:
    type: boolean
    default: false

jobs:
  php-build:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - composer/install:
          working-dir: php
      - run:
          working_directory: php
          command: composer lint && composer test

workflows:
  run-php:
    when: << pipeline.parameters.php-modified >>
    jobs:
      - php-build
