# Config dedicated for php module
# All the resources must be prefixed with `php-` to avoid conflicts

version: 2.1

orbs:
  composer: stockfiller/composer@1.0.0

executors:
  php:
    docker:
      - image: cimg/php:8.1

jobs:
  php-build:
    executor:
      name: php
    steps:
      - checkout
      - composer/install:
          working-dir: php
      - run:
          working_directory: php
          command: composer lint && composer test

workflows:
  php-workflow:
    jobs:
      - common-pre
      - php-build:
          requires:
            - common-pre
