# Config dedicated for js module
# All the resources must be prefixed with `js-` to avoid conflicts

version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:16.8.0-browsers

jobs:
  js-build:
    executor:
      name: node
    steps:
      - node/install-npm
      - checkout
      - node/install-packages:
          app-dir: js
      - run:
          working_directory: js
          command: npm test

workflows:
  js-workflow-x:
    jobs:
      - common-pre
      - js-build:
          requires:
            - common-pre
