# Config dedicated for e2e module
# All the resources must be prefixed with `e2e-` to avoid conflicts

version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  e2e-build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - node/install-npm:
          version: '16'
      - node/install-packages:
          app-dir: e2e
      - run:
          working_directory: e2e
          command: |
            sudo apt-get update && sudo apt-get install php php-xml
            npm run wp-env start
            npm test

workflows:
  e2e-workflow:
    jobs:
      - common-pre
      - e2e-build:
          requires:
            - common-pre
